#############################
### ENVIRONMENT VARIABLES ###
#############################

# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Wayland backend preference
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# Desktop/session identification
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Qt
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# Firefox (Wayland nativo)
env = MOZ_ENABLE_WAYLAND,1

# Java apps (algumas UIs bugadas sem isso)
env = _JAVA_AWT_WM_NONREPARENTING,1

# Electron apps (Discord, VSCode, Obsidian etc.)
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Portal GTK / file picker
env = GTK_USE_PORTAL,1