#############
### INPUT ###
#############

input {
    # Teclado
    kb_layout = br
    kb_variant = abnt2

    # Mouse global
    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat
    force_no_accel = true

    # Numlock ao iniciar
    numlock_by_default = true

    # Touchpad
    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
        drag_lock = false
        middle_button_emulation = false
        scroll_factor = 1.0
    }
}

# Gestos
gesture = 3, horizontal, workspace

# Mouse específico
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}