##############################
### WINDOWS AND WORKSPACES ###
##############################

# ---------------------------
# Window Rules
# ---------------------------

windowrule {
    name = fullscreen-opaque
    match:fullscreen = 1
    opacity = 1.0 override 1.0 override 1.0 override
    no_blur = 1
}   

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

#transparent apps
windowrule {
    name = transparent-vscode
    match:class = (code)$
    opacity = 0.95
}

windowrule {
    name = transparent-dolphin
    match:class = (org.kde.dolphin)$
    opacity = 0.90
}

windowrule {
    name = transparent-volume
    match:class = (org.pulseaudio.pavucontrol)$=
    opacity = 0.9
    float = yes
    size = 800 600
}

windowrule {
    name = transparent-ytmusic
    match:class = ^(YouTube Music Desktop App)$

    opacity = 0.90
}